# Generated by Django 4.2.29 on 2026-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
